### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by AndreasNel** [dutoitduard/ansipy#1]
Things that we would like to implement:

- [ ] Setup CI with Travis
- [ ] Publish library with pip OR deploy with Docker
- [ ] Python script to run Ansible playbooks
